// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZ7qXa4eBtHDGDsJDaLCNEekKjFS9IR_8',
    appId: '1:260332284190:web:1d608e5a2425d0245a010f',
    messagingSenderId: '260332284190',
    projectId: 'expensex-eaef8',
    authDomain: 'expensex-eaef8.firebaseapp.com',
    storageBucket: 'expensex-eaef8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbydOye3Ayi1COCXEfa8pxIEx6bwaeGcE',
    appId: '1:260332284190:android:aa3b4c6cf001bd215a010f',
    messagingSenderId: '260332284190',
    projectId: 'expensex-eaef8',
    storageBucket: 'expensex-eaef8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfFCdkKVDCICn4TyYfCrdI0C70eHBGw24',
    appId: '1:260332284190:ios:1bd4a6370c338ab95a010f',
    messagingSenderId: '260332284190',
    projectId: 'expensex-eaef8',
    storageBucket: 'expensex-eaef8.firebasestorage.app',
    iosBundleId: 'com.example.expensex',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfFCdkKVDCICn4TyYfCrdI0C70eHBGw24',
    appId: '1:260332284190:ios:1bd4a6370c338ab95a010f',
    messagingSenderId: '260332284190',
    projectId: 'expensex-eaef8',
    storageBucket: 'expensex-eaef8.firebasestorage.app',
    iosBundleId: 'com.example.expensex',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZ7qXa4eBtHDGDsJDaLCNEekKjFS9IR_8',
    appId: '1:260332284190:web:eef86cfe3e5d9b155a010f',
    messagingSenderId: '260332284190',
    projectId: 'expensex-eaef8',
    authDomain: 'expensex-eaef8.firebaseapp.com',
    storageBucket: 'expensex-eaef8.firebasestorage.app',
  );
}
